[package]
name = "apngquant"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
imagequant = "3.0.3"
png = "0.17.1"
